package aiegui.message;
// Generated Sep 10, 2018 5:10:08 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private int id;
     private Integer sourceSystemId;
     private Integer systemId;
     private Integer destinationSystemId;
     private Integer interfaceId;
     private String airport;
     private Integer messageType;
     private Integer messageSubType;
     private String messageId;
     private String correlationId;
     private String uuid;
     private String message;
     private String rawMessage;
     private String rawMessageType;
     private String errorCode;
     private Date stoDate;
     private Date stoTime;
     private String flightNumber;
     private String icaoAirline;
     private String iataAirline;
     private Date datetime;
     private Boolean accepted;
     private Boolean cachePopulated;
     private Integer messageCacheId;

    public Message() {
    }

	
    public Message(int id) {
        this.id = id;
    }
    public Message(int id, Integer sourceSystemId, Integer systemId, Integer destinationSystemId, Integer interfaceId, String airport, Integer messageType, Integer messageSubType, String messageId, String correlationId, String uuid, String message, String rawMessage, String rawMessageType, String errorCode, Date stoDate, Date stoTime, String flightNumber, String icaoAirline, String iataAirline, Date datetime, Boolean accepted, Boolean cachePopulated, Integer messageCacheId) {
       this.id = id;
       this.sourceSystemId = sourceSystemId;
       this.systemId = systemId;
       this.destinationSystemId = destinationSystemId;
       this.interfaceId = interfaceId;
       this.airport = airport;
       this.messageType = messageType;
       this.messageSubType = messageSubType;
       this.messageId = messageId;
       this.correlationId = correlationId;
       this.uuid = uuid;
       this.message = message;
       this.rawMessage = rawMessage;
       this.rawMessageType = rawMessageType;
       this.errorCode = errorCode;
       this.stoDate = stoDate;
       this.stoTime = stoTime;
       this.flightNumber = flightNumber;
       this.icaoAirline = icaoAirline;
       this.iataAirline = iataAirline;
       this.datetime = datetime;
       this.accepted = accepted;
       this.cachePopulated = cachePopulated;
       this.messageCacheId = messageCacheId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getSourceSystemId() {
        return this.sourceSystemId;
    }
    
    public void setSourceSystemId(Integer sourceSystemId) {
        this.sourceSystemId = sourceSystemId;
    }
    public Integer getSystemId() {
        return this.systemId;
    }
    
    public void setSystemId(Integer systemId) {
        this.systemId = systemId;
    }
    public Integer getDestinationSystemId() {
        return this.destinationSystemId;
    }
    
    public void setDestinationSystemId(Integer destinationSystemId) {
        this.destinationSystemId = destinationSystemId;
    }
    public Integer getInterfaceId() {
        return this.interfaceId;
    }
    
    public void setInterfaceId(Integer interfaceId) {
        this.interfaceId = interfaceId;
    }
    public String getAirport() {
        return this.airport;
    }
    
    public void setAirport(String airport) {
        this.airport = airport;
    }
    public Integer getMessageType() {
        return this.messageType;
    }
    
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }
    public Integer getMessageSubType() {
        return this.messageSubType;
    }
    
    public void setMessageSubType(Integer messageSubType) {
        this.messageSubType = messageSubType;
    }
    public String getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }
    public String getCorrelationId() {
        return this.correlationId;
    }
    
    public void setCorrelationId(String correlationId) {
        this.correlationId = correlationId;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public String getRawMessage() {
        return this.rawMessage;
    }
    
    public void setRawMessage(String rawMessage) {
        this.rawMessage = rawMessage;
    }
    public String getRawMessageType() {
        return this.rawMessageType;
    }
    
    public void setRawMessageType(String rawMessageType) {
        this.rawMessageType = rawMessageType;
    }
    public String getErrorCode() {
        return this.errorCode;
    }
    
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }
    public Date getStoDate() {
        return this.stoDate;
    }
    
    public void setStoDate(Date stoDate) {
        this.stoDate = stoDate;
    }
    public Date getStoTime() {
        return this.stoTime;
    }
    
    public void setStoTime(Date stoTime) {
        this.stoTime = stoTime;
    }
    public String getFlightNumber() {
        return this.flightNumber;
    }
    
    public void setFlightNumber(String flightNumber) {
        this.flightNumber = flightNumber;
    }
    public String getIcaoAirline() {
        return this.icaoAirline;
    }
    
    public void setIcaoAirline(String icaoAirline) {
        this.icaoAirline = icaoAirline;
    }
    public String getIataAirline() {
        return this.iataAirline;
    }
    
    public void setIataAirline(String iataAirline) {
        this.iataAirline = iataAirline;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public Boolean getAccepted() {
        return this.accepted;
    }
    
    public void setAccepted(Boolean accepted) {
        this.accepted = accepted;
    }
    public Boolean getCachePopulated() {
        return this.cachePopulated;
    }
    
    public void setCachePopulated(Boolean cachePopulated) {
        this.cachePopulated = cachePopulated;
    }
    public Integer getMessageCacheId() {
        return this.messageCacheId;
    }
    
    public void setMessageCacheId(Integer messageCacheId) {
        this.messageCacheId = messageCacheId;
    }




}


